import Link from 'next/link';import {Shell,PageHero} from '../components/site';
const pages:any={
sectors:['Sectors','Occupational health shaped around your working environment.','Construction & infrastructure|Manufacturing & engineering|Transport & logistics|Public sector|Healthcare & care|Office & professional'],
'mobile-units':['Mobile occupational health','Bring the clinic to the workforce.','Six-unit mobile fleet|Two large two-person units|Four smaller one-person units|Sound-proof hearing booths|Portable screening equipment|UK-wide delivery'],
employers:['For employers','One connected route from referral to outcome.','Management referrals|Health surveillance programmes|Employee status and recalls|Mobile-unit requests|Employer reports|Secure document access'],
employees:['For employees','Clear information before, during and after occupational health.','What to expect|Confidentiality and consent|Preparing for an appointment|Accessing your information|Workplace adjustments|Questions and support'],
resources:['Resources','Practical occupational-health guidance for employers and employees.','Management referral guide|Health surveillance guide|Safety-critical medicals|Drug & alcohol testing|Mobile-unit site preparation|Employee appointment guide'],
about:['About WorkWell by OHI','Modern occupational health built around people and work.','UK-wide service delivery|Experienced clinical team|Mobile occupational health|Employer-focused systems|Confidential employee journeys|Practical workplace advice'],
governance:['Clinical governance','Safe, accountable clinical delivery.','Clinical leadership|Scope of practice|Consent and confidentiality|Quality assurance|Incident management|Audit and improvement'],
accreditations:['Accreditations','Standards, memberships and evidence in one place.','Professional registrations|Clinical competency|Quality controls|Information governance|Training records|Supplier assurance'],
'standards-security':['Standards & security','Privacy-first occupational-health systems.','UK GDPR and Data Protection Act alignment|Role-based access|Clinical and employer data separation|Encryption and secure hosting|Audit logging|Retention and deletion controls'],
'production-blueprint':['Production blueprint','How the demo becomes a production occupational-health platform.','Next.js public website|Secure employer portal|Employee journey|Clinician workspace|B2B commerce|UK/Australia-ready architecture'],
careers:['Careers','Help build a better occupational-health experience.','Occupational-health nurses|Doctors and physicians|Technicians|Administration|Client services|Digital and operations'],
faq:['Frequently asked questions','Straight answers about occupational health.','How quickly can an appointment be arranged?|Can services be delivered on site?|What does my employer receive?|How is clinical information protected?|Can we buy services online?|Do you provide UK-wide coverage?'],
privacy:['Privacy','How information is handled across the WorkWell journey.','Data minimisation|Lawful processing|Clinical confidentiality|Individual rights|Retention controls|Processor and supplier governance'],
accessibility:['Accessibility','A service designed to be usable by as many people as possible.','Keyboard navigation|Clear focus states|Readable contrast|Responsive layouts|Plain-language content|Alternative support routes'],
terms:['Terms','Clear terms for using WorkWell services and digital systems.','Website use|Service ordering|Appointments|Cancellations|Employer responsibilities|Digital platform terms']};
export const contentPageTypes=Object.keys(pages);
export function ContentPage({type}:{type:string}){const p=pages[type];if(!p)return null;return <Shell><PageHero eyebrow={p[0]} title={p[1]} intro="WorkWell by OHI combines practical occupational-health delivery with a clearer digital experience."/><section className="section"><div className="wrap grid3">{p[2].split('|').map((x:string,i:number)=><div className="card" key={x}><span className="badge">{String(i+1).padStart(2,'0')}</span><h3>{x}</h3><p>Built into the WorkWell service model with clear ownership, appropriate governance and a straightforward user journey.</p></div>)}</div><div className="wrap cta-panel"><div><h2>Need something specific?</h2><p>Tell us what you are trying to achieve and we will route you to the right service.</p></div><Link className="btn primary" href="/what-do-i-need">Tell us what you need</Link></div></section></Shell>}
