const services = [
  ['◉','Health surveillance','Audiometry, lung function, HAVS, eyesight, skin, musculoskeletal and general health surveillance based around workplace risk.','/services'],
  ['＋','Workplace medicals','Medical assessment pathways for forklift truck operators, working at height, confined spaces and other safety-relevant roles.','/services'],
  ['◇','Drug & alcohol','Workplace drug and alcohol testing, including chain-of-custody requirements where appropriate.','/services'],
  ['↗','New starter health','Role-aware pre-placement pathways that can route employees to the right questionnaire, review or clinical assessment.','/services'],
  ['☰','Management referral','Securely refer an employee for occupational-health advice, with case status and employer-appropriate outcomes kept in one place.','/portal'],
  ['▰','On-site screening','Bring OHI to your workplace and build a screening day around your workforce, risks and operational requirements.','/contact'],
];

export default function Home(){
  return <main className="signed-demo" id="top">
    <div className="sd-topline"><div className="sd-wrap"><span>Occupational health and mobile health surveillance across the UK</span><span>01253 366156 &nbsp; · &nbsp; admin@ohihealthessentials.co.uk</span></div></div>
    <header className="sd-header"><nav className="sd-wrap sd-nav">
      <a className="sd-logo" href="#top"><div className="sd-mark">ohi</div><div><strong>OHI</strong><small>WORKPLACE HEALTH</small></div></a>
      <div className="sd-links"><a href="#services">Services</a><a href="#mobile">Mobile units</a><a href="#industries">Industries</a><a href="#commerce">Online services</a><a href="#about">About OHI</a></div>
      <div className="sd-actions"><a className="sd-btn paper" href="/portal">Employer login</a><a className="sd-btn dark" href="/services">Buy & book</a></div>
    </nav></header>

    <div className="sd-wrap"><section className="sd-hero">
      <div className="sd-hero-copy"><span className="sd-eyebrow">Occupational health that works around your workplace</span><h1>Better health at work. Less disruption.</h1><p>Practical occupational health, workforce screening and mobile surveillance for employers across the UK, with a simpler way to buy, book and manage services online.</p><div className="sd-hero-actions"><a className="sd-btn acid" href="/services">What do I need?</a><a className="sd-btn paper" href="/services">Buy a service</a></div></div>
      <div className="sd-hero-visual"><div className="sd-hero-note"><strong>We come to you.</strong><span>Mobile occupational health screening helps reduce employee travel and workplace downtime.</span></div><div className="sd-truck-zone"><img src="https://www.ohihealthessentials.co.uk/images/ohi-truck1.png" alt="OHI mobile health screening unit" /></div></div>
    </section>
    <div className="sd-band"><div><strong>UK-wide</strong><span>Mobile health surveillance</span></div><div><strong>On site</strong><span>Less time away from work</span></div><div><strong>Risk-led</strong><span>Services shaped around need</span></div><div><strong>Online</strong><span>Buy, book and manage</span></div></div></div>

    <section id="services" className="sd-section"><div className="sd-wrap"><div className="sd-section-head"><div><div className="sd-kicker">Core services</div><h2>From one assessment to a whole workforce programme.</h2></div><p>OHI's existing service range has been reorganised into a modern employer journey, with direct routes into the commerce platform.</p></div><div className="sd-cards">{services.map(([icon,title,copy,href])=><article className="sd-card" key={title}><div className="sd-icon">{icon}</div><h3>{title}</h3><p>{copy}</p><a href={href}>{title==='New starter health'?'Start a new-starter pathway':title==='Management referral'?'Create a referral':title==='On-site screening'?'Plan an on-site day':'View services'} →</a></article>)}</div></div></section>

    <section className="sd-section soft"><div className="sd-wrap"><div className="sd-pathway"><div className="sd-path-intro"><div className="sd-kicker" style={{color:'#d7ec74'}}>OHI Assist</div><h2>Don't know which service to order?</h2><p>The website should not expect an employer to understand occupational-health terminology. Start with what is happening in the workplace and let OHI guide the route.</p><a className="sd-btn acid" href="/services">Start the guided assessment</a></div><div className="sd-path-options"><a className="sd-path" href="/services"><strong>I have a new employee</strong><span>Pre-placement and role-specific assessment</span></a><a className="sd-path" href="/portal"><strong>An employee is off sick</strong><span>Management referral and OH advice</span></a><a className="sd-path" href="/services"><strong>I need health surveillance</strong><span>Build the right surveillance programme</span></a><a className="sd-path" href="/contact"><strong>I need OHI at our site</strong><span>Mobile screening and workforce booking</span></a></div></div></div></section>

    <section id="mobile" className="sd-section"><div className="sd-wrap"><div className="sd-mobile-unit"><div className="sd-mobile-copy"><div className="sd-kicker">Mobile occupational health</div><h2>Take the clinic to the workforce.</h2><p>OHI already delivers mobile health surveillance. The new digital platform makes that operational strength much easier to buy: define the site, employee numbers and tests, then move directly into the booking workflow.</p><div className="sd-checks"><span>✓ Audiometry</span><span>✓ Lung function</span><span>✓ HAVS</span><span>✓ Eyesight</span><span>✓ Health assessments</span><span>✓ Medicals</span></div><a className="sd-btn dark" href="/contact">Plan a mobile screening day</a></div><div className="sd-mobile-image"><img src="https://www.ohihealthessentials.co.uk/images/ohi-truck1.png" alt="OHI mobile health screening vehicle" /></div></div></div></section>

    <section id="industries" className="sd-section"><div className="sd-wrap"><div className="sd-section-head"><div><div className="sd-kicker">Sector experience</div><h2>Occupational health built around the risk, not a generic package.</h2></div><p>OHI supports organisations across construction, civil engineering, steel, manufacturing, energy, transport, public services and other safety-critical environments.</p></div><div className="sd-cards"><article className="sd-card"><div className="sd-icon">⌂</div><h3>Construction & engineering</h3><p>Risk-based health surveillance, safety-critical medicals and efficient on-site delivery.</p><a href="/industries">Build a programme →</a></article><article className="sd-card"><div className="sd-icon">⚙</div><h3>Manufacturing & industrial</h3><p>Surveillance programmes for noise, respiratory exposure, vibration and role-specific risks.</p><a href="/industries">Build a programme →</a></article><article className="sd-card"><div className="sd-icon">▦</div><h3>Public & service sectors</h3><p>Flexible occupational-health support for distributed teams and varied job roles.</p><a href="/contact">Talk to OHI →</a></article></div></div></section>

    <section id="commerce" className="sd-section"><div className="sd-wrap"><div className="sd-commerce"><div><div className="sd-kicker" style={{color:'#d7ec74'}}>OHI Commerce</div><h2>From website visit to completed OH workflow.</h2><p>The website does the explaining. Commerce handles purchasing, referrals and bookings. The employer workspace then provides a single view of orders, employee status, upcoming surveillance and appropriate outcomes.</p><div className="sd-hero-actions"><a className="sd-btn acid" href="/services">Open OHI Commerce</a><a className="sd-btn paper" href="/portal">Employer workspace</a></div></div><div className="sd-commerce-ui"><div className="sd-mini-row"><div><strong>Health surveillance</strong><br/><small>Risk-led workplace programme</small></div><span className="sd-pill">View details</span></div><div className="sd-mini-row"><div><strong>Management referral</strong><br/><small>Employer case pathway</small></div><span className="sd-pill">Buy online</span></div><div className="sd-mini-row"><div><strong>Mobile screening day</strong><br/><small>Tailored workplace delivery</small></div><span className="sd-pill">Build a quote</span></div></div></div></div></section>

    <footer id="about" className="sd-footer"><div className="sd-wrap"><div className="sd-footgrid"><div><a className="sd-logo" href="#top"><div className="sd-mark">ohi</div><div><strong>OHI</strong><small style={{color:'#9db7af'}}>WORKPLACE HEALTH</small></div></a><p>Occupational health built around people, workplaces and better operational decisions.</p></div><div><h4>Services</h4><a href="/services">Health surveillance</a><a href="/services">Workplace medicals</a><a href="/services">Drug & alcohol testing</a></div><div><h4>Employers</h4><a href="/portal">Employer portal</a><a href="/contact">Mobile screening</a><a href="/industries">Industries</a></div><div><h4>Contact</h4><p>312 Central Drive<br/>Blackpool, FY1 6LE</p><a href="tel:01253366156">01253 366156</a><a href="mailto:admin@ohihealthessentials.co.uk">admin@ohihealthessentials.co.uk</a></div></div><div className="sd-copyright"><span>© 2026 OHI Health Essentials Ltd.</span><span>Staging demonstration · synthetic data only</span></div></div></footer>
  </main>
}
