'use client';import {useEffect,useState} from 'react';import Link from 'next/link';import {VERSION} from '../components/site';
const clients=[
{name:'Northshore Engineering Ltd',people:84,status:'Active',next:'Noise surveillance · 12 Sep',risk:'Green'},
{name:'Blackpool Logistics Group',people:46,status:'Action due',next:'Safety critical reviews · 05 Sep',risk:'Amber'},
{name:'Meridian Fabrication',people:112,status:'Active',next:'HAVS programme · 18 Sep',risk:'Green'}
];
const people=[
{name:'Alex Morgan',company:'Northshore Engineering Ltd',service:'Health surveillance',stage:'Clinical review',tests:'Audiometry complete · Spirometry complete',result:'Review required'},
{name:'Jamie Patel',company:'Blackpool Logistics Group',service:'Safety-critical medical',stage:'Report ready',tests:'Vision pass · Hearing pass · BP recorded',result:'Fit'},
{name:'Taylor Reed',company:'Meridian Fabrication',service:'HAVS surveillance',stage:'Assessment due',tests:'Tier 1 complete',result:'Pending'}
];
const reports=[
{title:'Noise surveillance programme summary',client:'Northshore Engineering Ltd',date:'31 Aug 2026',status:'Ready'},
{title:'Safety-critical fitness outcomes',client:'Blackpool Logistics Group',date:'30 Aug 2026',status:'Ready'},
{title:'HAVS recall schedule',client:'Meridian Fabrication',date:'29 Aug 2026',status:'Draft'}
];
const serviceLinks=[['Health surveillance','/health-surveillance'],['Management referral','/management-referral'],['Safety-critical medicals','/safety-critical-medicals'],['Drug & alcohol testing','/drug-alcohol-testing'],['Pre-placement health','/pre-placement-health'],['Workplace vaccinations','/workplace-vaccinations']];
export default function Portal(){const[role,setRole]=useState('employer');const[view,setView]=useState('dashboard');const[selected,setSelected]=useState<any>(null);const[note,setNote]=useState('');useEffect(()=>{const r=sessionStorage.getItem('workwell-demo-role');if(r)setRole(r)},[]);const nav=role==='clinician'?['dashboard','queue','tests','reports']:role==='employee'?['dashboard','appointments','documents','results']:['dashboard','clients','people','reports','services'];return <div className="portal-shell"><aside className="portal-side"><Link href="/" className="portal-brand"><b>WorkWell</b><span>{VERSION}</span><small>DEMO PORTAL</small></Link><div className="role-switch"><button onClick={()=>{setRole('employer');setView('dashboard')}} className={role==='employer'?'active':''}>Employer</button><button onClick={()=>{setRole('employee');setView('dashboard')}} className={role==='employee'?'active':''}>Employee</button><button onClick={()=>{setRole('clinician');setView('dashboard')}} className={role==='clinician'?'active':''}>Clinician</button></div><nav>{nav.map(n=><button key={n} className={view===n?'active':''} onClick={()=>{setView(n);setSelected(null)}}>{n[0].toUpperCase()+n.slice(1)}</button>)}</nav><Link className="btn soft" href="/login">Change demo login</Link></aside><main className="portal-main"><div className="demo-banner">DEMO DATA ONLY · No real employee, clinical or employer records are stored here.</div><div className="portal-top"><div><span className="badge">{role.toUpperCase()} WORKSPACE</span><h1>{view[0].toUpperCase()+view.slice(1)}</h1></div><div className="portal-user">Demo {role}<small>Signed in</small></div></div>{selected?<Detail item={selected} role={role} note={note} setNote={setNote} back={()=>setSelected(null)}/>:<View role={role} view={view} setSelected={setSelected}/>}</main></div>}
function View({role,view,setSelected}:{role:string;view:string;setSelected:(x:any)=>void}){if(role==='employee')return <EmployeeView view={view} setSelected={setSelected}/>;if(role==='clinician')return <ClinicianView view={view} setSelected={setSelected}/>;if(view==='clients')return <PortalTable title="Client organisations" rows={clients} setSelected={setSelected}/>;if(view==='people')return <PortalTable title="People & examination status" rows={people} setSelected={setSelected}/>;if(view==='reports')return <PortalTable title="Employer reports" rows={reports} setSelected={setSelected}/>;if(view==='services')return <div className="portal-grid">{serviceLinks.map(([name,href])=><Link href={href} className="portal-card" key={href}><span className="badge">Service</span><h3>{name}</h3><p>Open the full public demo service specification.</p></Link>)}</div>;return <><div className="portal-stats"><Stat n="242" l="Employees covered"/><Stat n="18" l="Assessments this week"/><Stat n="7" l="Reports ready"/><Stat n="3" l="Actions due"/></div><div className="portal-grid"><PortalTable title="Recent clients" rows={clients.slice(0,2)} setSelected={setSelected}/><PortalTable title="Latest reports" rows={reports.slice(0,2)} setSelected={setSelected}/></div></>}
function EmployeeView({view,setSelected}:{view:string;setSelected:(x:any)=>void}){const me={name:'Jordan Ellis',employer:'Northshore Engineering Ltd',service:'Health surveillance',nextAppointment:'12 Sep 2026 · 10:30',location:'OHI Mobile Unit · Site A',status:'Appointment booked'};if(view==='appointments')return <PortalTable title="Appointments" rows={[me]} setSelected={setSelected}/>;if(view==='documents')return <PortalTable title="My documents" rows={[{title:'Appointment information',date:'01 Sep 2026',status:'Available'},{title:'Consent information',date:'01 Sep 2026',status:'Available'}]} setSelected={setSelected}/>;if(view==='results')return <PortalTable title="My outcomes" rows={[{service:'Audiometry',date:'12 Mar 2026',result:'No change requiring action'},{service:'Respiratory surveillance',date:'12 Mar 2026',result:'Routine recall'}]} setSelected={setSelected}/>;return <><div className="portal-stats"><Stat n="12 Sep" l="Next appointment"/><Stat n="2" l="Documents"/><Stat n="Mar 2027" l="Next recall"/></div><div className="portal-card"><span className="badge">NEXT APPOINTMENT</span><h2>{me.service}</h2><p>{me.nextAppointment}</p><p>{me.location}</p><button className="btn primary" onClick={()=>setSelected(me)}>View appointment details</button></div></>}
function ClinicianView({view,setSelected}:{view:string;setSelected:(x:any)=>void}){if(view==='queue')return <PortalTable title="Clinical queue" rows={people} setSelected={setSelected}/>;if(view==='tests')return <PortalTable title="Tests awaiting review" rows={people.map(p=>({...p,action:'Open test record'}))} setSelected={setSelected}/>;if(view==='reports')return <PortalTable title="Reports awaiting clinical action" rows={reports} setSelected={setSelected}/>;return <><div className="portal-stats"><Stat n="11" l="Assessments today"/><Stat n="4" l="Awaiting review"/><Stat n="3" l="Reports to sign"/><Stat n="1" l="Recall action"/></div><PortalTable title="Today’s clinical queue" rows={people} setSelected={setSelected}/></>}
function PortalTable({title,rows,setSelected}:{title:string;rows:any[];setSelected:(x:any)=>void}){return <section className="portal-card"><h2>{title}</h2><div className="portal-table">{rows.map((r,i)=><button key={i} onClick={()=>setSelected(r)}><span><b>{r.name||r.title||r.service}</b><small>{r.company||r.client||r.employer||r.date}</small></span><span>{r.status||r.stage||r.result||'Open'} →</span></button>)}</div></section>}
function Detail({item,role,note,setNote,back}:{item:any;role:string;note:string;setNote:(x:string)=>void;back:()=>void}){return <div className="portal-card detail-record"><button className="btn soft" onClick={back}>← Back</button><span className="badge">DEMO RECORD</span><h2>{item.name||item.title||item.service}</h2><div className="record-grid">{Object.entries(item).map(([k,v])=><div key={k}><small>{k.replace(/([A-Z])/g,' $1')}</small><b>{String(v)}</b></div>)}</div>{role==='clinician'&&<><h3>Clinical test capture</h3><div className="test-grid"><label>Blood pressure<input placeholder="e.g. 128/78"/></label><label>Vision<input placeholder="Pass / value"/></label><label>Hearing<input placeholder="Result / threshold"/></label><label>Spirometry<input placeholder="FEV1 / FVC"/></label><label>Outcome<select><option>Pending review</option><option>Fit</option><option>Fit with restrictions</option><option>Further assessment</option></select></label></div><label className="notes-label">Clinical notes<textarea rows={6} value={note} onChange={e=>setNote(e.target.value)} placeholder="Demo clinical notes..."/></label><button className="btn primary" onClick={()=>alert('Demo only: assessment saved locally for presentation purposes.')}>Save demo assessment</button></>}</div>}
function Stat({n,l}:{n:string;l:string}){return <div className="portal-stat"><b>{n}</b><span>{l}</span></div>}
