import {NextResponse} from 'next/server';
import {commerceServices} from '../../../data/commerce';
import {createOrder,markWorkflowReady,newAccessToken,newOrderId,updateOrder,type CommerceOrder} from '../../../lib/commerce-store';
import {createXeroInvoice} from '../../../lib/xero';

export const runtime='nodejs';
type CheckoutBody={serviceSlug?:string;paymentMethod?:'card'|'invoice';organisation?:string;email?:string;poNumber?:string};
function baseUrl(req:Request){return process.env.NEXT_PUBLIC_APP_URL||new URL(req.url).origin}
function workflowType(slug:string):CommerceOrder['workflow']['type']{if(slug.includes('management-referral'))return 'referral';if(slug.includes('surveillance')||slug.includes('audiometry')||slug.includes('spirometry')||slug.includes('havs'))return 'surveillance';if(slug.includes('medical')||slug.includes('drug')||slug.includes('vaccination'))return 'booking';return 'order'}
async function stripeCheckout(req:Request,order:CommerceOrder,service:{slug:string;name:string;pricePence:number}){
 const key=process.env.STRIPE_SECRET_KEY;if(!key)throw new Error('Stripe is not configured on this environment.');
 const body=new URLSearchParams();body.set('mode','payment');body.set('success_url',`${baseUrl(req)}/portal/orders?placed=1&order=${encodeURIComponent(order.id)}&token=${encodeURIComponent(order.accessToken)}`);body.set('cancel_url',`${baseUrl(req)}/checkout?service=${encodeURIComponent(service.slug)}`);body.set('customer_email',order.email);body.set('client_reference_id',order.id);body.set('metadata[ohi_order_id]',order.id);body.set('metadata[organisation]',order.organisation);body.set('line_items[0][quantity]','1');body.set('line_items[0][price_data][currency]','gbp');body.set('line_items[0][price_data][unit_amount]',String(service.pricePence));body.set('line_items[0][price_data][product_data][name]',service.name);
 const response=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/x-www-form-urlencoded'},body,cache:'no-store'});const json=await response.json();if(!response.ok)throw new Error(json?.error?.message||'Stripe checkout could not be created.');return {id:json.id as string,url:json.url as string};
}
export async function POST(req:Request){try{
 const body=(await req.json()) as CheckoutBody;const service=commerceServices.find(s=>s.slug===body.serviceSlug);if(!service||service.pricePence===null)return NextResponse.json({error:'This service cannot be checked out at a fixed price.'},{status:400});if(!body.organisation?.trim()||!body.email?.trim())return NextResponse.json({error:'Organisation and billing email are required.'},{status:400});const now=new Date().toISOString();
 const order:CommerceOrder={id:newOrderId(),accessToken:newAccessToken(),createdAt:now,updatedAt:now,serviceSlug:service.slug,service:service.name,totalPence:service.pricePence,currency:'GBP',organisation:body.organisation.trim(),email:body.email.trim().toLowerCase(),poNumber:body.poNumber?.trim()||null,paymentMethod:body.paymentMethod==='invoice'?'invoice':'card',paymentStatus:body.paymentMethod==='invoice'?'invoice-draft':'pending',workflow:{type:workflowType(service.slug),status:'pending-finance',workItemId:null}};await createOrder(order);
 if(order.paymentMethod==='invoice'){const xero=await createXeroInvoice({orderId:order.id,service:service.name,pricePence:service.pricePence,organisation:order.organisation,email:order.email,poNumber:order.poNumber||''});const status=(xero.status||'DRAFT').toUpperCase();const paymentStatus=status==='PAID'?'invoice-paid':status==='AUTHORISED'?'invoice-authorised':'invoice-draft';let updated=await updateOrder(order.id,{xeroInvoiceId:xero.invoiceId,xeroInvoiceNumber:xero.invoiceNumber,paymentStatus});if(paymentStatus==='invoice-authorised'||paymentStatus==='invoice-paid')updated=await markWorkflowReady(order.id);return NextResponse.json({order:updated,accessToken:order.accessToken})}
 const stripe=await stripeCheckout(req,order,{slug:service.slug,name:service.name,pricePence:service.pricePence});await updateOrder(order.id,{stripeCheckoutSessionId:stripe.id});return NextResponse.json({order:{id:order.id},provider:'stripe',url:stripe.url});
 }catch(error){console.error('[commerce checkout]',error);return NextResponse.json({error:error instanceof Error?error.message:'Checkout failed.'},{status:500})}}
