'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {QRCodeSVG} from 'qrcode.react';
import {Shell,PageHero} from '../components/site';

const DEMO_SECRET='JBSWY3DPEHPK3PXP';
const ISSUER='WorkWell by OHI';
function base32ToBytes(input:string){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';for(const ch of input.replace(/=+$/,'').toUpperCase()){const v=alphabet.indexOf(ch);if(v<0)continue;bits+=v.toString(2).padStart(5,'0')}const out:number[]=[];for(let i=0;i+8<=bits.length;i+=8)out.push(parseInt(bits.slice(i,i+8),2));return new Uint8Array(out)}
async function currentTotp(secret:string,offset=0){const counter=Math.floor(Date.now()/1000/30)+offset;const msg=new ArrayBuffer(8);new DataView(msg).setUint32(4,counter,false);const key=await crypto.subtle.importKey('raw',base32ToBytes(secret),{name:'HMAC',hash:'SHA-1'},false,['sign']);const sig=new Uint8Array(await crypto.subtle.sign('HMAC',key,msg));const o=sig[sig.length-1]&15;const bin=((sig[o]&127)<<24)|((sig[o+1]&255)<<16)|((sig[o+2]&255)<<8)|(sig[o+3]&255);return String(bin%1000000).padStart(6,'0')}

export default function MfaSetupPage(){const [code,setCode]=useState('');const [status,setStatus]=useState('');const [verified,setVerified]=useState(false);const [account,setAccount]=useState('demo.clinician@workwell.test');const [alreadyEnabled,setAlreadyEnabled]=useState(false);const [next,setNext]=useState('/portal');const [required,setRequired]=useState(false);
 useEffect(()=>{const params=new URLSearchParams(window.location.search);setNext(params.get('next')||'/portal');setRequired(params.get('required')==='1');const email=sessionStorage.getItem('workwell-demo-email')||'demo.clinician@workwell.test';setAccount(email);setAlreadyEnabled(localStorage.getItem(`workwell-demo-mfa-enabled:${email}`)==='1')},[]);
 const uri=useMemo(()=>`otpauth://totp/${encodeURIComponent(ISSUER)}:${encodeURIComponent(account)}?secret=${DEMO_SECRET}&issuer=${encodeURIComponent(ISSUER)}&algorithm=SHA1&digits=6&period=30`,[account]);
 async function verify(e:React.FormEvent){e.preventDefault();const candidates=await Promise.all([-1,0,1].map(x=>currentTotp(DEMO_SECRET,x)));if(candidates.includes(code.replace(/\s/g,''))){localStorage.setItem(`workwell-demo-mfa-enabled:${account}`,'1');sessionStorage.setItem('workwell-demo-mfa-verified','1');setAlreadyEnabled(true);setVerified(true);setStatus('Authenticator code verified successfully.')}else{setStatus('That code did not match. Wait for a fresh six-digit code and try again.')}}
 const heading=alreadyEnabled?'Confirm your authenticator code.':'Add WorkWell to your authenticator in seconds.';const intro=alreadyEnabled?'MFA is already enrolled for this demo account. Enter the current six-digit code to complete this sign-in.':'Scan the QR code with a standards-based authenticator app, then enter the six-digit code to verify enrolment. This demonstrates the intended TOTP user experience; production secrets will be generated and stored server-side.';
 return <Shell><PageHero eyebrow={required?'DEMO · MFA required':'DEMO · Multi-factor authentication'} title={heading} intro={intro}/><section className="section"><div className="wrap detail-layout">{!alreadyEnabled&&<div className="card form-card"><span className="badge">TOTP authenticator setup</span><h2>1. Scan the QR code</h2><div style={{background:'#fff',padding:20,border:'1px solid #dbe7e3',borderRadius:18,width:'fit-content'}}><QRCodeSVG value={uri} size={220} level="M" marginSize={2}/></div><p>Open Google Authenticator, Microsoft Authenticator, 1Password or another TOTP-compatible app and scan this code.</p><h3>Can’t scan it?</h3><p>Enter this setup key manually:</p><code style={{display:'block',padding:14,borderRadius:12,background:'#f4f8f6',color:'#102d2a',fontWeight:800,letterSpacing:2,overflowWrap:'anywhere'}}>{DEMO_SECRET}</code><p><b>Account:</b> {account}<br/><b>Type:</b> Time based<br/><b>Digits:</b> 6<br/><b>Period:</b> 30 seconds</p></div>}
 <form className="card form-card" onSubmit={verify}><span className="badge">{alreadyEnabled?'MFA challenge':'Verification'}</span><h2>{alreadyEnabled?'Confirm sign-in':'2. Confirm your authenticator'}</h2><label>Six-digit code<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="123456" required/></label><button className="btn primary" type="submit">{alreadyEnabled?'Verify code':'Verify and enable MFA'}</button>{status&&<p className={verified?'success-note':'login-error'} role="status">{status}</p>}{verified&&<><div className="success-note"><b>MFA verified</b><p>This demo session has passed its second-factor check. Production recovery codes and account-reset controls will be securely managed server-side.</p></div><Link className="btn dark" href={next}>Continue to demo portal</Link></>}</form></div></section><section className="section band"><div className="wrap"><span className="kicker">Production security model</span><h2>MFA will be more than a QR screen.</h2><div className="grid3"><div className="card"><h3>Required for privileged roles</h3><p>Clinician and administrator accounts will require MFA, with policy controls available for employers.</p></div><div className="card"><h3>Server-side secrets</h3><p>TOTP seeds will be generated securely, encrypted at rest and never exposed again after enrolment except through controlled recovery/re-enrolment.</p></div><div className="card"><h3>Recovery and audit</h3><p>Recovery codes, MFA resets, failed challenges and enrolment changes will be audited and protected by re-authentication.</p></div></div></div></section></Shell>}
