'use client';
import {useMemo,useState} from 'react';
import Link from 'next/link';
import {QRCodeSVG} from 'qrcode.react';
import {Shell,PageHero} from '../components/site';

const DEMO_SECRET='JBSWY3DPEHPK3PXP';
const ISSUER='WorkWell by OHI';
const ACCOUNT='demo.clinician@workwell.test';

function base32ToBytes(input:string){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';for(const ch of input.replace(/=+$/,'').toUpperCase()){const v=alphabet.indexOf(ch);if(v<0)continue;bits+=v.toString(2).padStart(5,'0')}const out:number[]=[];for(let i=0;i+8<=bits.length;i+=8)out.push(parseInt(bits.slice(i,i+8),2));return new Uint8Array(out)}
async function currentTotp(secret:string,offset=0){const counter=Math.floor(Date.now()/1000/30)+offset;const msg=new ArrayBuffer(8);const view=new DataView(msg);view.setUint32(4,counter,false);const key=await crypto.subtle.importKey('raw',base32ToBytes(secret),{name:'HMAC',hash:'SHA-1'},false,['sign']);const sig=new Uint8Array(await crypto.subtle.sign('HMAC',key,msg));const o=sig[sig.length-1]&15;const bin=((sig[o]&127)<<24)|((sig[o+1]&255)<<16)|((sig[o+2]&255)<<8)|(sig[o+3]&255);return String(bin%1000000).padStart(6,'0')}

export default function MfaSetupPage(){
 const [code,setCode]=useState('');const [status,setStatus]=useState('');const [enabled,setEnabled]=useState(false);
 const uri=useMemo(()=>`otpauth://totp/${encodeURIComponent(ISSUER)}:${encodeURIComponent(ACCOUNT)}?secret=${DEMO_SECRET}&issuer=${encodeURIComponent(ISSUER)}&algorithm=SHA1&digits=6&period=30`,[]);
 async function verify(e:React.FormEvent){e.preventDefault();const candidates=await Promise.all([-1,0,1].map(x=>currentTotp(DEMO_SECRET,x)));if(candidates.includes(code.replace(/\s/g,''))){setEnabled(true);setStatus('MFA verified successfully. This demo device is now enrolled for presentation purposes.')}else{setStatus('That code did not match. Wait for a fresh six-digit code in your authenticator and try again.')}}
 return <Shell><PageHero eyebrow="DEMO · Multi-factor authentication" title="Add WorkWell to your authenticator in seconds." intro="Scan the QR code with a standards-based authenticator app, then enter the six-digit code to verify enrolment. This page proves the intended TOTP user experience; production secrets will be generated and stored server-side."/>
 <section className="section"><div className="wrap detail-layout"><div className="card form-card"><span className="badge">TOTP authenticator setup</span><h2>1. Scan the QR code</h2><div style={{background:'#fff',padding:20,border:'1px solid #dbe7e3',borderRadius:18,width:'fit-content'}}><QRCodeSVG value={uri} size={220} level="M" marginSize={2}/></div><p>Open Google Authenticator, Microsoft Authenticator, 1Password or another TOTP-compatible app and scan this code.</p><h3>Can’t scan it?</h3><p>Enter this setup key manually:</p><code style={{display:'block',padding:14,borderRadius:12,background:'#f4f8f6',fontWeight:800,letterSpacing:2,overflowWrap:'anywhere'}}>{DEMO_SECRET}</code><p><b>Account:</b> {ACCOUNT}<br/><b>Type:</b> Time based<br/><b>Digits:</b> 6<br/><b>Period:</b> 30 seconds</p></div>
 <form className="card form-card" onSubmit={verify}><span className="badge">Verification</span><h2>2. Confirm your authenticator</h2><label>Six-digit code<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="123456" required/></label><button className="btn primary" type="submit">Verify and enable MFA</button>{status&&<p className={enabled?'success-note':'login-error'}>{status}</p>}{enabled&&<><div className="success-note"><b>Recovery codes</b><p>Production will generate single-use recovery codes after enrolment, display them once, and store only secure hashes.</p></div><Link className="btn dark" href="/portal">Continue to demo portal</Link></>}</form></div></section>
 <section className="section band"><div className="wrap"><span className="kicker">Production security model</span><h2>MFA will be more than a QR screen.</h2><div className="grid3"><div className="card"><h3>Required for privileged roles</h3><p>Clinician and administrator accounts will require MFA, with policy controls available for employers.</p></div><div className="card"><h3>Server-side secrets</h3><p>TOTP seeds will be generated securely, encrypted at rest and never exposed again after enrolment except through controlled recovery/re-enrolment.</p></div><div className="card"><h3>Recovery and audit</h3><p>Recovery codes, MFA resets, failed challenges and enrolment changes will be audited and protected by re-authentication.</p></div></div></div></section></Shell>}
